### ISSUE TITLE
Download method no more working, streaming does.

### ISSUE THREAD

**Issue by mkkyah** [danielvijge/SqueezeCloud#17] opened 2017-03-09 07:26 UTC
Hi,
I don't know if this is new, but if you choose "play method" as "always use download method if available" in plugin settings, no track is playing anymore. But good news, streaming method is working for all so far.
Seeking in tracks still not working.
Squeezeplug v0.9.1  on Logitech Media Server Version: 7.9.0 - 1485445004

**Comment by danielvijge** [comment] 2017-03-14 18:47
Cannot reproduce this. Tried playing tracks from 'Tim Sweeney (Beats in Space)'. Tracks are available as both stream and download. Both play methods work correctly. Do you have some specific tracks that fail to play?

Playing with LMS7.9.0 (1488878280) on a Squeezebox Touch.

**Comment by mkkyah** [comment] 2017-03-14 19:12
Yes, you're right Tim Sweeney  BIS tracks are playing, but almost none of my stream tracks are playable. Try:
https://soundcloud.com/ninja-tune/sets/actress-x22rme
or
https://soundcloud.com/hyenahmusic/the-wish-ft-butiza-free-download

and I have only this track playing on my stream, maybe you can find something: https://soundcloud.com/george_xtzs/london-grammar-hey-now-george-x-bootleg

**Comment by danielvijge** [comment] 2017-03-14 21:37
With the track 
https://soundcloud.com/hyenahmusic/the-wish-ft-butiza-free-download I can reproduce the issue. The problem is with the download setting. Soundcloud returns a download URL, but at the same time indicates that the track is not downloadable. Some extra checks should solve this. I have already written some code, but want to test it before I release a new version.
In the meantime, if you really want to play those tracks, in the Soundcloud settings from LMS, switch from download method to stream method.

**Comment by mkkyah** [comment] 2017-03-15 07:25
I'm glad you have found it, sure we can wait for the tests. I will also check and report after the release.
Is there an improvement with "seek in tracks"?

**Comment by danielvijge** [comment] 2017-03-25 11:09
Fixed by 6271f25c653a1878f0ad7743aee922a19cd4ede9

Seek in tracks still not working, no idea why

**Closed by danielvijge** 2017-03-25 11:09 UTC

**Comment by mkkyah** [comment] 2017-03-26 13:33
I can confirm, it's working again with the upgrade. Additionally I can play and add (multiple track) soundcloud playlists now.

**Comment by mkkyah** [comment] 2017-03-26 16:54
I have found some issues:
--with mobile controllers (orange squeeze, Squeeze Ctrl, ipeng) some tracks are playing a totally different list of tracks. Actually a playlist is added, but not from the stream or any known place, totally random to me. Web qui is adding/playing correct track. BUT if I play these tracks from web gui, than mobile apps cannot change the track, nothing happens if I click a normally playable track. I have to change it with web gui or play a track from other plugin or source. Play mode is not changing this behaivour.
try: https://soundcloud.com/lars_neubert/sets/fabel-37-lars-neubert-1
or  https://soundcloud.com/dgtl-festival/jennifer-cardini-axel-boman-dgtl-podcast-45

--Some tracks are not playing with download method. (all controllers)
try: https://soundcloud.com/gabrielsordo/gabriel-sordo-rodriguez-jj-drop-dance-mix-edit-mstr

**Comment by mkkyah** [comment] 2017-03-26 18:56
> --with mobile controllers (orange squeeze, Squeeze Ctrl, ipeng) some tracks are playing a totally different list of tracks. Actually a playlist is added, but not from the stream or any known place, totally random to me. 

With further testing, this is happening if any mobile app's default play mode  is set to prompt (when a track is tapped). If you choose "play" when tapped, it's not happening. 
[If that helps, there is a similar issue with Mixcloud plugin's "New Mixes", but I could not workaround that issue with turning prompt setting off. (and in that case a different track from the same list is played)]

I think this last upgrade has broken some working codes for direct streaming mode. Yes, download mode is playing tracks, but streaming mode is failing now for a lot of tracks.
Please tell me , if you need sample links.

**Comment by mkkyah** [comment] 2017-03-26 20:05
> I think this last upgrade has broken some working codes for direct streaming mode. Yes, download mode is playing tracks, but streaming mode is failing now for a lot of tracks.

Sorry, this is not true.
Streaming method plays most of the tracks, but not with mobile apps. This track is a good example, it's playing with web gui in streaming mode, but not with apps (in both play modes). Not playing in download mode, either web gui nor apps.

there are 2 playlists with multiple tracks, the first is adding the tracks and playing them. The second is not playing with both web gui and apps:
https://soundcloud.com/wonderwheel-recordings/sets/dj-khalab-baba-sissoko-khalab-and-baba-remixes
https://soundcloud.com/katermukke/sets/lars-moston-good-times-feat-isis-salam-kater139
Things are getting better, if I paste direct url of the last playlist, all 4 tracks in the playlist are added and  playing.

I have created a test playlist (tracks only): https://soundcloud.com/mkkyah/sets/test/s-rwUhN

**Comment by danielvijge** [comment] 2017-03-27 07:16
Thanks for testing it. I think the wrong number played is the same at #11 , but I will do some further testing based on your comments.

**Comment by mkkyah** [comment] 2017-03-27 16:23
--I think, with mobile apps, if the tap/direct play is selected, the first 8 tracks are playing normal, than it starts to play the 2 or 3 tracks before the tapped one. I couldn't document the exact pattern. This is same for the Squeezecloud and Mixcloud apps. So, try to test with long lists of tracks. After a while on the list it starts to reject all of them to play, but the first 8. So it's not always a "playable track" issue.
I remember that #11 and I think it's no more happening as before,  maybe transformed to this with api changes.
-- There are still some tracks not playing with download mode.
-- And there is that weird  problem, if you tap and choose from prompted options (defeat setting from players or similar options from apps) very unexpected tracks are loading to playlist.
