### ISSUE TITLE
Wrong item played when selecting from SoundCloud playlists

### ISSUE THREAD

**Issue by schnillerman** [danielvijge/SqueezeCloud#26] opened 2020-05-22 07:08 UTC
When selecting a song from a SoundCloud playlist to be added to cue or to be played, playlist entry 2 before selected song is played. If playlist only contains 2 entries, nothing is played. If playlist contains only 1 entry, that entry is played (works as expected).

Version info:

**Server**

Version: 8.0.0 - 1589867264 @ Tue May 19 08:18:49 CEST 2020
Hostname: LMS
IP-Adresse des Servers: 192.168.1.102
Betriebssystem: Debian - DE - utf8
Plattformarchitektur: x86_64-linux
Perl-Version: 5.24.1 - x86_64-linux-gnu-thread-multi
Audio::Scan: 0.95
IO::Socket::SSL: 2.044
Datenbankversion: DBD::SQLite 1.58 (sqlite 3.22.0)

**Plugins**

Band's Campout 1.7.6
Drag & Drop Musikdateien zur Wiedergabe 0.1
Dynamic Mix 1.3
Erweiterte Musik Menüs 1.0
Geräte Gruppen 0.11.0
Info-Browser 1.0
Last.fm Audioscrobbler 1.0
LastMix 2.0.0
Lesezeichen 1.2.22
Live Music Archive 1.0
Material Skin 1.6.0
Mixcloud 0.2.1
Musik- und Interpreten-Information 1.6.17
Musiksammlung erneut durchsuchen 1.0
Musikwiedergabe nie anhalten 1.0.0
mysqueezebox.com-Service Handler 1.0
Netzwerktest 1.0
NoSetup - Einstellungen aus-/einblenden 2.5.2
Online Musiksammlungsintegration 1.0
Orange Liveradio 1.0
Radio 1.0
Radio Paradise 3.1.0
RadioFeeds UK & Ireland 1.02
Song Info 1.1.3883
Song Lyrics 1.1.3856
SoundCloud 0.9.4
SyncOptions 2.2.4
Titel-Scanner 2.0
Volltextsuche 1.0.0
Was lief da eben? 1.0.7
Wefunk Radio 0.3.3
Wiedergabeliste speichern 1.0
Wiedergabelisten-Manager 6.1
Zufallsmix 1.0

**Comment by danielvijge** [comment] 2020-08-07 11:17
Duplicate of #21

**Closed by danielvijge** 2020-08-07 11:17 UTC
